import type { Metadata } from "next";

import DetailPageNav from "@/app/(Components)/Nav/DetailPageNav";

export const metadata: Metadata = {
  title: "detail page",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
