import type { Metadata } from "next";

import TopNav from "@/app/(Components)/Nav/TopNav";
import Footer from "@/app/(Components)/Footer";

import "../../../styles/styles.scss";

export const metadata: Metadata = {
  title: "Detail Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <TopNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
