import type { Metadata } from "next";

import TopNav from "@/app/(Components)/Nav/TopNav";
import Footer from "@/app/(Components)/Footer";

import "../../../styles/styles.scss";
import AuthSession from "@/app/(provider)/AuthSession";
export const metadata: Metadata = {
  title: "Detail Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body suppressHydrationWarning={true}>
        <AuthSession>
          <TopNav />
          {children}
          <Footer />
        </AuthSession>
      </body>
    </html>
  );
}
