import type { Metadata } from "next";
import AuthSession from "@/app/(provider)/AuthSession";


import "../../../styles/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <AuthSession>
          <main className="main-login">{children}</main>{" "}
        </AuthSession>
      </body>
    </html>
  );
}
