import type { Metadata } from "next";

import "../../../styles/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <main className="main-login">{children}</main>{" "}
      </body>
    </html>
  );
}
