import type { Metadata } from "next";

import TopNav from "./(Components)/TopNav";
import Footer from "./(Components)/Footer";

import "../styles/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <TopNav />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
