//@ts-nocheck
import type { Metadata } from "next";
import DetailPageNav from "@/app/(Components)/Nav/DetailPageNav";
import { URL } from "@/app/(util)/CATEGORY";
import { getShoppingMallPage } from "@/app/(http)/apis/productApi";
export const metadata: Metadata = {
  title: "detail page",
  description: "Generated by create next app",
};

async function getData(searchParams) {
  const shoppingMallData = await getShoppingMallPage(searchParams);
  return {
    category1List: shoppingMallData.categ1List,
  }
}
export default async function Layout(
  { children, searchParams }:
    { children: React.ReactNode }
) {
  const data = await getData(searchParams);
  return (
    <>
      <DetailPageNav pageType={URL.SHOPPING} navList={data.category1List} />
      {children}
    </>
  );
}
