//@ts-nocheck
import type { Metadata } from "next";
import DetailPageNav from "@/app/(Components)/Nav/DetailPageNav";
import { URL } from "@/app/(util)/CATEGORY";
import { getShoppingMallPage } from "@/app/(http)/apis/productApi";
export const metadata: Metadata = {
  title: "detail page",
  description: "Generated by create next app",
};

async function getData() {
  const shoppingMallData = await getShoppingMallPage();
  return {
    category1List: shoppingMallData.categ1List,
  }
}
export default async function Layout({ children }: { children: React.ReactNode }) {
  const data = await getData();
  return (
    <>
      <DetailPageNav pageType={URL.SHOPPING} navList={data.category1List} />
      {children}
    </>
  );
}
